[package]
name = "star"
version = "0.1.0"
description = "Deterministic tool, field, and box framework"
repo = "https://github.com/XxingGoD/star"

[targets.star]
kind = "bin"
main = "src/main.cpp"

[dependencies.nlohmann]
json = "3.12.0"

[dependencies.marzer]
tomlplusplus = "3.4.0"

[dependencies.mcpplibs.capi]
lua = "0.0.3"

[toolchain]
default = "gcc@16.1.0"
macos = "llvm@20.1.7"
windows = "llvm@22.1.8"

[target.x86_64-linux-musl]
toolchain = "gcc@15.1.0-musl"
linkage = "static"

[target.aarch64-linux-musl]
linkage = "static"
